[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$EoLw3ntPSSkFYCwFwNg7hw$X68FVmE3kyQxGylShroqmEoGmgoH9V7uhQPYvg9Fb63MspnmlKGucvbfYUjjMLMIchBBLxrIlxHpNsTKalNzFw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

